---
title: "Lab 3"
author: "Danny Ettelson"
date: "1/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###0. Attach Packages

```{r loadlib}


library(tidyverse)
library(boot)
library(naniar)
library(simputation)


```

###A. Bootstrapping penguin flipper lengths

1. Get penguin data

```{r}

penguins <- read_csv("penguins.csv")

male_p <- penguins %>% 
  filter(sex == "MALE")

# LOOK AT IT

ggplot(male_p, aes(x = flipper_length)) +
  geom_histogram(bins = 10) +
  theme_classic()


flippers <- male_p %>% 
  pull(flipper_length)

```

###Create a Function, and do some bootstrapping


```{r}

mean_fun <- function(x,i) { mean(x[i])}

set.seed(42)

boot_10 <- boot(flippers, mean_fun, R = 10)

boot_100 <- boot(flippers, mean_fun, R = 100)

boot_10000 <- boot(flippers, mean_fun, R = 10000)


ggplot() +
  aes(boot_10000$t) +
  geom_histogram()

#Calculate the confidence interval using the boot.ci() function in the boot package

boot.ci(boot_10000, conf = 0.95)


```

### Evaluating missingness with naniar




```{r}

vis_miss(airquality)

gg_miss_var(airquality, facet = Month)

#Functions to work with ggplot
#geom_miss_point()

ggplot(airquality,
       aes(x = Ozone,
                       y = Solar.R)) +
  geom_miss_point()

ggplot(airquality, 
       aes(x = Solar.R,
           y = Temp)) +
  geom_miss_point() +
  scale_color_manual(values = c("orange","purple")) +
  facet_wrap(~Month)

#complete.cases() returns T/F which entries have all fields complete

#Creating a shadow matrix

na_shadow <- bind_shadow(airquality)

# Imputation by linear regression

airquality %>% 
  impute_lm(Ozone ~ Temp + Wind) %>% 
  ggplot(aes(x = Temp, y = Ozone)) +
  geom_point()

na_shadow %>% 
  impute_lm(Ozone ~ Temp + Wind) %>% 
  ggplot( aes( x = Temp, y = Ozone, color = Ozone_NA)) +
  geom_point()


```





